### ISSUE TITLE
[B] 트래킹 전 오류

### ISSUE THREAD

**Issue by rose6649** [boostcampwm-2021/iOS01-Booster#184]
- 내용
트래킹하려고 탭 들어갔는데, 권한이 없어서 설정들어가서 권한 채우고 다시 트래킹 시작하려고 앱 들어왔는데
트래킹 탭에서 오류가 나면서 꺼집니당

- 정상 시나리오
정상적으로 트래킹이 시작되어야 해요

- 첨부 파일
![image](https://user-images.githubusercontent.com/42143611/143684932-e4569dce-bc34-4110-a958-0d387ac8ba0e.png)

**Comment by KTH-INHA-16** [comment]
그 권한이 무슨 권한일까요?
