### ISSUE TITLE
[B-28] 트래킹 중 걸음 수 오류

### ISSUE THREAD

**Issue by rose6649** [boostcampwm-2021/iOS01-Booster#25]
- 내용
트래킹 중 마일스톤을 찍고 난 뒤 걸음수가 다시 0으로 시작하는 현상

- 정상 시나리오
마일스톤 찍고 나서도 걸음수가 유지돼서 보여야 합니다

- 첨부 파일
 ㅠ.ㅠ

**Comment by Hani-Levenshtein** [comment]
ㅜ
