### ISSUE TITLE
DailyScrum: Day10

### ISSUE THREAD

**Issue by s1gnature** [boostcampwm-2021/iOS01-Booster#26]
### Todo 🚀🔥
1. 어제 한 일 🌄

2. 오늘 할 일 🌅

### 회고 📆📝
> 당신의 오늘 하루는 어땠나요?? ☺️
>

**Comment by Hani-Levenshtein** [comment]
Todo 🚀🔥

어제 한 일 🌄
- 발표 자료 준비하기

오늘 할 일 🌅
- 다른 팀 구경하기

회고 📆📝

쏘쏘

**Comment by s1gnature** [comment]
### Todo 🚀🔥
1. 어제 한 일 🌄
코드 프리징을 위한 작업 완료 및 발표 자료 만들기
2. 오늘 할 일 🌅
다른 팀 진행 상황 파악 및 우리 팀으로 가져오면 좋은 것들 참고하기
### 회고 📆📝
> 드디어 개발 1주차가 끝이 났습니다! 생각보다 우리팀 진도가 빠른 것 같기도 하고 많은 것들을 느낄 수 있었어요!
> 앞으로 추가 작업 할 수 있다면 해당 부분에 대해 의논하는 것도 재밌을 것 같습니다~~
> 앞으로도 완성을 위해 달려봐요🔥🔥🔥🔥

**Comment by KTH-INHA-16** [comment]
Todo 🚀🔥
어제 한 일 🌄
Core Data 작업 까지 마무리하고 금요일 발표 자료 준비
오늘 할 일 🌅
Github 활용법 백배 익히기!
회고 📆📝
한주 끝났고 아직 3주 남았다 ㅠㅠ

**Comment by rose6649** [comment]
### Todo 🚀🔥
1. 어제 한 일 🌄
- 코드 프리징 & 영상 제작 발표 자료
2. 오늘 할 일 🌅
- 피드백, 버그 수정사항들 꼭꼭 확인하고 서로 코드 리뷰 받은거랑 내가 쓰지 않은 코드에 대한 이해를 좀 해오기 CoreLocation 등..

### 회고 📆📝
> 와우... 뭔가 길면서 짧은 개발 1주차였습니다.. 벌써 시간이 4주남았다니..?
> 너무 아쉽네요 ㅋㅋㅎㅎ 추가기능도 열시미 도입하고 싶네요! 하이팅입니다 부스터팀원~><
