### ISSUE TITLE
1주차 회고

### ISSUE THREAD

**Issue by s1gnature** [boostcampwm-2021/iOS01-Booster#7]
### 주간 회고
이번주 내용

다음주 내용
- 각 파트별로 HealthKit 과 MapKit에 대해 알아봅시다!

### 한마디씩 해주기(😈 덕담과 악담을 동시에!👼🏻 )
- 태훈
> 

- 명섭
>

- 하원
>

- 희주
>

**Comment by KTH-INHA-16** [comment]
주간 회고
이번주 내용
Booster를 기획, 디자인, 개발 요구사항 설정 및 역할 분담을 하였다.

다음주 내용
실제 Booster 개발 진행

각 파트별로 HealthKit 과 MapKit에 대해 알아봅시다!
한마디씩 해주기(😈 덕담과 악담을 동시에!👼🏻 )
태훈
- 명섭: 허리 안 좋으신데 직접 회의도 나오시느라 고생많으셨습니다!! 앞으로 같이 잘 진행해봐요!!
- 하원: 태훈님 얼굴 볼때마다 다리꼰걸 풀게되네여 감사합니다 ☺️
- 희주: 허리도 아프신데 첫날부터 신촌오시고.. 항상 많은 의견 내주셔서 감사해요ㅠㅠ 개발 함께 부딪혀봐요!~! 꼭 허리는 쾌차하셔야 합니다

명섭
- 태훈: 본인이 생각했던 기능들을 보완해주었고 놓쳤던 부분들을 채울 수 있어서 좋았음
- 하원: 발표대본 짜시느라 고생하셨습니다 믿음직스럽네여 ☺️
- 희주: 대본 취합하고 발표준비하시느라 수고많으셨어요 ㅠㅠ 선뜻 나서서 발표 좋아하신다고 해주셔서 얼마나 감사했는지 모름니다.. ㅎㅎ 이번주부터 개발 화이팅해봅시당!

하원
- 명섭: 스쳐 지나갈 수 있는 부분들에 대해서 다시 한 번 생각할 수 있도록 포인트를 잡아주셔서 좋았습니다!! 홈이랑 통계쪽 잘 부탁드릴게요~~
- 태훈: 기술적인 부분에서 약한 부분들을 잘 이야기 해주었고, 그 부분을 보완할 수 있는 선택지를 제공해주어서 감사합니다.
- 희주: 깐부… … 술은 금지구요.. 또 같이 하게 되서 사실 좋습니다 ㅎㅎ 꼼꼼한 실력을 가진 하원님.. 저의 둔한 부분들을 캐치해주세요! 이번주도 열심히 개발해봐요!

희주
- 명섭: 저희꺼 디자인이랑 발표자료 같이 만드시느라 고생 많으셨습니다!! 염치없지만 앞으로도 디자인 잘 부탁드려요..! 감사합니다~~
- 하원: 디자인하느라 고생이 많습니다 ☺️ 앞으로도 잘부탁드립니다
- 태훈: 디자인까지 해주셔서 너무 고생이 많습니다...... 앞으로도 잘 부탁드립니다~
